### ISSUE TITLE
Not working in gnome 3.32

### ISSUE THREAD

**Issue by tiotrom** [tomMoral/ToDoList#10]
As the title says :(

**Comment by Ravinou** [comment]
I confirm. Don't work with Ubuntu 19.04 :'(

Thank you !!

**Comment by meolivares06** [comment]
How can i get the data. Since it is not working, i lost it.

**Comment by Ravinou** [comment]
@meolivares06 
> How can i get the data. Since it is not working, i lost it.

Hello !
You can get back your data in a json file locate at : /home/user/.config/ToDoList/tasks.json

Have a good day ;)

**Comment by tomMoral** [comment]
As @Ravinou said, the data are stored in a json file in `$HOME/.config/ToDoList/tasks.json`.

Sorry I just saw this issue. I will try to fix this for gnome `3.32` asap.
