### ISSUE TITLE
Not working in Gnome 3.34

### ISSUE THREAD

**Issue by O-Gopal** [tomMoral/ToDoList#13]
Thank you for the excellent extension. But now that I've upgraded from Ubuntu 18.04 to 19.10 (Gnome 3.34.1), ToDoList doesn't run (message in Tweaks: "Error loading extension"). 

I attach a message from my log file. Perhaps this might be related; I don't know. 

Thanks again, and best wishes.

![Log message](https://user-images.githubusercontent.com/2028254/71349400-0015b980-2595-11ea-9b7d-f4481449ed14.png)

**Comment by cpazaras** [comment]
Not working for me either. Linux Manjaro, Gnome version 3.34.2, kernel version 4.19.91-1-MANJARO.

My log file, hope it helps:

```
Jan 06 13:30:49 manjaro gnome-shell[1462]: JS WARNING: [/home/user/.local/share/gnome-shell/extensions/todolist@tomMoral.org/gui_elements/section_item.js 60]: reference to undefined property "_rename"
Jan 06 13:30:49 manjaro gnome-shell[1462]: JS ERROR: Extension todolist@tomMoral.org: Error: second argument to Lang.bind() must be a function, not undefined
                                           bind@resource:///org/gnome/gjs/modules/lang.js:75:15
                                           SectionItem@/home/user/.local/share/gnome-shell/extensions/todolist@tomMoral.org/gui_elements/section_item.js:60:49
                                           _add_section@/home/user/.local/share/gnome-shell/extensions/todolist@tomMoral.org/gui_elements/todolist_display.js:137:20
                                           _fill_ui@/home/user/.local/share/gnome-shell/extensions/todolist@tomMoral.org/gui_elements/todolist_display.js:125:13
                                           _enable@/home/user/.local/share/gnome-shell/extensions/todolist@tomMoral.org/gui_elements/todolist_display.js:232:9
                                           enable@/home/user/.local/share/gnome-shell/extensions/todolist@tomMoral.org/extension.js:25:5
                                           _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:280:21
                                           _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:490:13
                                           collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                           _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:469:9
                                           _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:499:13
                                           _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:530:13
                                           init@resource:///org/gnome/shell/ui/extensionSystem.js:48:9
                                           _initializeUI@resource:///org/gnome/shell/ui/main.js:242:5
                                           start@resource:///org/gnome/shell/ui/main.js:138:5
                                           @<main>:1:31

```

**Comment by tomMoral** [comment]
Thanks a lot for the reports!

I finally find some time to try and fix this. It is now working under gnome3.34. Could you try the latest version and tell me if this fix your issues?

**Comment by O-Gopal** [comment]
I'm willing to try it but don't know how. I see the installation instructions: 

_Link the git folder in your gnome sheel extension repository (mine is ~/.local/share/gnome-shell/extensions/) as todolist@tomMoral.org Starting from the git repo:
$ ./install.sh
then restart you session Atl-F2 and r._
b
But I don't understand them. 

My extension repository is the same as yours. And I know how to restart a session. But (1) How does one "link the git folder"? and (2) how does one "start from the git repo"? I'd need a step-by-step of what to do. 

My apologies for my ignorance.

**Comment by tomMoral** [comment]
Sorry that the guidance are not easy to follow.
`gnome-shell` discovers all extensions in the extension repository so to install the extension, you can simply copy the folder `todolist@tommoral.org` in the extension repository.

To allow on the fly modification of the repo, I usually don't do a copy but a symbolic link. So when I say link the folder `todolist@tomMoral.org` in the extension, I mean creating a symbolic link with `ln`. This is basically what is done if you run the script `install.sh` which is in the git repo. So a step by step would be:
```
$ cd /path/to/todolist/repo
$ . install.sh
```
And then restart the session. This should get you set up.

Another option is to install the extension from gnome extension website, I put an up to date version yesterday.

**Comment by O-Gopal** [comment]
Thank you. It installed from your posted update. 
ToDo List shows up again in the top bar. The tasks show up. I can add new tasks and subtasks. But when I "unfold" a task the area for subtasks appears almost entirely black. (See sample below.) I've tried various themes -- Yaru, Yaru Light, Yaru Dark, and Radiance -- and the issue persists. Thank you for the progress so far!
![ToDo List--subtasks--03-01-20](https://user-images.githubusercontent.com/2028254/75625420-ab567680-5bb5-11ea-9f88-394918a66152.png)

**Comment by tomMoral** [comment]
It is probably due to the fact that I developped everything with the dark theme in mind. sorry about that.

You can modify that in the `stylesheet.css`. It should work if you insert the following line in l.83:
```
	color: rgb(204, 204, 204);
```

If you have any idea on how to use the theme colors instead of fixed ones, I would be happy to improve the integration in gnome.

**Comment by cpazaras** [comment]
Just wanted to confirm that it works for me now as well.
(Manjaro, Gnome 3.34.4, dark theme).
@tomMoral thanks for maintaining!

**Comment by tomMoral** [comment]
Great! I am now under gnome3.36 and it is also working so we are fine for some time!
I am closing the issue then, feel free to open a new one if other problems appears.

**Comment by O-Gopal** [comment]
Sorry to be slow to comment.

That CCS revision does indeed fix the subtasks. But now the tasks 
themselves appear in grey. Can you suggest which CSS value to change?

Sorry, but I have no clue how to use theme colors instead of fixed ones.



> It is probably due to the fact that I developped everything with the 
> dark theme in mind. sorry about that.
>
> You can modify that in the |stylesheet.css|. It should work if you 
> insert the following line in l.83:
>
> |color: rgb(204, 204, 204); |
>
> If you have any idea on how to use the theme colors instead of fixed 
> ones, I would be happy to improve the integration in gnome.
>

**Comment by O-Gopal** [comment]
I made these changes to the CSS file: 

        .task-item{
	     background-color: AntiqueWhite;

        .task-label{
             color: black

That makes all look fine to me with a light theme. 

Thank you again.
