### ISSUE TITLE
ToDo list disappeared from top bar

### ISSUE THREAD

**Issue by deepcharles** [tomMoral/ToDoList#3]
The todolist disappeared when I started my computer. Before that it worked for a time until I wasn't able to write any new section (I could write but they disappeared when I pressed "enter").

Ubuntu 16.04.1 LTS 64-bit
GNOME Shell 3.18.5

**Comment by tomMoral** [comment]
This come from the fact that section should not contains "/" as their name is use to create a file.

**Comment by tomMoral** [comment]
This should be solved in the latest version.
