### ISSUE TITLE
Insecure task

### ISSUE THREAD

**Issue by KSXGitHub** [tomMoral/ToDoList#4]
I had a look at `$HOME/.config/ToDoList` recently (I faced some problems while using your package) and see that you save tasks as files so if normal users create the some tasks with dangerous name (e.g. `clean /home`, `/usr`, or `/whatever /contains /slash`) they won't be able to recover from accident.

**My suggestion:** Do one of these things:

1. Prevent users from creating these dangerous name. Also, `section` should be preserved (There's a file called `section.tasks`)

2. JSON is cool and JavaScript friendly, why not just use them?

**Comment by tomMoral** [comment]
Thanks for the insights!
It is true that there is an issue with the file names being the sections tests.
I will move it to JSON as soon as I have some spare time. It makes more sense to have only one saving file.

That being said, it should not be unsafe for your system as the file names are created in `$HOME/.config/ToDoList`. So except if you put a task with a lot of `..` you won't break your system.

**Comment by tomMoral** [comment]
Ok this should be solved now.

Note that it is true for the github version, I need to update the extension.gnome.org version.
