### ISSUE TITLE
Double click to rename doesn't work

### ISSUE THREAD

**Issue by stevenpost** [tomMoral/ToDoList#8]
Version: 5
Gnome 3.22
OS: Debian Stable 9 (up-to-date)

Double clicking a section or task selects the word, clicking 3 times selects the whole line, but I'm not able to edit an existing task or section.

**Comment by tomMoral** [comment]
Hi,

Thanks for testing and reporting this bug!
I think you should be able to edit task and section with a single click so it is weird it is not editable in your case.. I will try and investigate this!

Could you try to launch the following command in a terminal:
```
journalctl /usr/bin/gnome-shell -f -o cat | grep -E -e "ToDo|JS ERROR" #|  sed -e 's/ JS LOG://'
```
and interact with the todolist. Try adding a section, removing it and them clicking on one section to edit. I hope this could give me an idea of what is going on so I can fix it.

**Comment by stevenpost** [comment]
Hi,

It does seem to work with a single click (I didn't know it could do that), but it is a bit hard to get right when wanting a cursor on the end of the section/task.
It seems that this isn't a bug in the code, but in the documentation. The README.md file says:
Double click to rename a Section/Task

```
# journalctl /usr/bin/gnome-shell -f -o cat | grep -E -e "ToDo|JS ERROR" #|  sed -e 's/ JS LOG://'
JS LOG: [ToDo] - DEBUG - Got section with name: test section
JS LOG: [ToDo] - DEBUG - Emit signals
JS LOG: [ToDo] - DEBUG - Rename tasktest task to edited task
```

**Comment by tomMoral** [comment]
Thanks for reporting back! I will indeed update the `README.md`.

As for the cursor, on my machine, the mouse changes to a `I` when I hoover over the text so it is not so hard to select the end of the line. Do you see the same behavior?

**Comment by stevenpost** [comment]
Yes, but there's just not that much space between the last character and the end of the line, making it a bit hard to get right, of course it also depends on the mouse sensitivity, mine is set quite sensitive.
If you could just update the README.md file, I'll consider this fixed.

Also, my apologies for not getting back to you before today, it seems I'm not receiving the github notifications as I was expecting.

**Comment by tomMoral** [comment]
No problem for the delay, I just got back from vacation!
I updated the `README.md`.

**Comment by stevenpost** [comment]
Then I'm considering this solved :)

PS: I fixed my notifications, the primary e-mail address was no longer in use (former employer)
